=== Genesis2412/ZoomaliaRedo/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--Global variable for id-->
  <xs:simpleType name="idCheck">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value = "1"/>
      <xs:maxInclusive value = "70"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Global variable for Type-->
  <xs:simpleType name="typeCheck">
    <xs:restriction base="xs:string">
      <xs:pattern value="Cat|Dog"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Global variable for Name-->
  <xs:simpleType name="nameCheck">
    <xs:restriction base="xs:string">
      <xs:minLength value="5"/>
      <xs:maxLength value="30"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Global variable for Description-->
  <xs:simpleType name="descriptionCheck">
    <xs:restriction base="xs:string">
      <xs:minLength value="10"/>
      <xs:maxLength value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Global variable for currency-->
  <xs:simpleType name = "currencyCheck">
    <xs:restriction base="xs:string">
      <xs:pattern value="Rs|rs"/>
    </xs:restriction>
  </xs:simpleType>
    

  <!--Global variable for product-->
  <xs:element name="product">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Type" type="typeCheck"/>
        <xs:element name="Name" type="nameCheck"/>
        <xs:element name="Description" type="descriptionCheck"/>
        <xs:element name="Price">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:decimal">
                <xs:attribute name="currency" type="currencyCheck"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="img" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="id" type="idCheck"/>
    </xs:complexType>
  </xs:element>

  <!--product Schema-->
  <xs:element name="products">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="product" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>  
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Genesis2412/ZoomaliaRedo/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="products.xsl"?>
<products xs:noNamespaceSchemaLocation = "products.xsd" xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance">

  <product id="1">
        <Name>Dog Collar</Name>
        <Description>Red collar with paw prints</Description>
        <Price currency="Rs">200.00</Price>
        <img>y1.jpg</img>
        <dogProducts category="Dog Collar"></dogProducts>
  </product>
  
  <product id="2">
        <Name>Dog Harness</Name>
        <Description>Adjustable harness with leash lead set</Description>
        <Price currency="Rs">600.00</Price>
        <img>y3.jpg</img>
        <dogProducts category="Dog Harness"></dogProducts>
  </product>
  
  <product id="3">
        <Name>Dog Brush</Name>
        <Description> Puppy grooming brush</Description>
        <Price currency="Rs">150.00</Price>
        <img>y5.jpg</img> 
        <dogProducts category="Dog Brush"></dogProducts>
  </product>
  
  <product id="4">
        <Name>Dog Leash </Name>
        <Description>Simple red dog leash</Description>
        <Price currency="Rs">200.00</Price>
        <img>y7.jpg</img>
        <dogProducts category="Dog Leash"></dogProducts>
  </product>
  
  <product id="5">
        <Name>Dog Toys</Name>
        <Description> Includes 4 types of dog toys</Description>
        <Price currency="Rs">250</Price>
        <img>y9.jpg</img>
        <dogProducts  category="Dog Toys"></dogProducts>
  </product>
  
  <product id="6">
        <Name>Dog Kennel</Name>
        <Description> Black modular kennel </Description>
        <Price currency="Rs">1500</Price>
        <img>y11.jpg</img>
        <dogProducts category="Dog Kennel"></dogProducts>
  </product>
  
  <product id="7">
       <Name>Cat Collar</Name>
        <Description>Luxury green cat collar</Description>
        <Price currency="Rs">300</Price>
        <img>z1.jpg</img> 
        <catProducts category="Cat Collar"></catProducts>
  </product>
  
  <product id="8">
        <Name>Cat Harness</Name>
        <Description>Lightweight, soft and breatheable</Description>
        <Price currency="Rs">500.50</Price>
        <img>z3.jpg</img>
        <catProducts category="Cat Harness"></catProducts>
  </product>
  
  <product id="9">
        <Name>Cat Toys</Name>
        <Description> Small toy fish and feather</Description>
        <Price currency="Rs">100</Price>
        <img>z5.jpg</img>
        <catProducts category="Cat Toys"></catProducts>
  </product>
  
  <product id="10">
        <Name>Cat Bed</Name>
        <Description>Indoor cat bed</Description>
        <Price currency="Rs">450</Price>
        <img>z7.jpg</img>
        <catProducts category="Cat Bed"></catProducts>
  </product>
</products>
